### ISSUE TITLE
Insert all Line inputs into as head text

### ISSUE THREAD

**Issue by PaulAnderie** [prandible/cf7-sevdesk#4]
The first two items (Line item 1 and Line Item 2) should be inserted as an additional head text and should not live as individual positions.

**Comment by PaulAnderie** [comment]
Hey @cezarys in my test szenario the line item 1 and 2 as well as the $Rechnungsadresse input wasn't displayed in the header content. 

Can you check that again, pls?
![Bildschirmfoto_2019-04-05_um_09_32_19](https://user-images.githubusercontent.com/30237486/55611821-fa6a1080-5786-11e9-9e90-8a1da8fce8cd.png)

**Comment by cezarys** [comment]
that is weird, because it should - I don't even see the header text from WYSIWYG editor there

**Comment by PaulAnderie** [comment]
yes, @cezarys I've tested that on a local site on my computer, but with the new sevdesk account. Is it running on your end?

**Comment by cezarys** [comment]
@PaulAnderie Yes it is, I'm testing on my server

**Comment by cezarys** [comment]
@PaulAnderie I have an idea - please copy-paste what you inputed in header and footer field to my server 

http://www.cezary-siwa.com/sevdesk/wp-admin/admin.php?page=sevdesk_config

admin
!Password!

Maybe there is some weird speciach character which breaks everything?

**Comment by PaulAnderie** [comment]
Hey @cezarys  yes, that was due to an emoji, I've used :D we don't need to care about that. 

It's working and I'll close this issue
