### ISSUE TITLE
Default Head and Footer text

### ISSUE THREAD

**Issue by PaulAnderie** [prandible/cf7-sevdesk#5]
Can we create an html ready text field in the backend, where we can insert default head and footer text, which will be pasted into sevdesk after form submit? Pls keep in mind the point no. 4, where we need to add the selected line items into the head text as well.
![Bildschirmfoto_2019-04-03_um_09_20_13](https://user-images.githubusercontent.com/30237486/55460332-096b8a00-55f2-11e9-9db4-5d8214ce08cb.png)

**Comment by PaulAnderie** [comment]
Hey @cezarys do I need to fill out for every form the header and footer text box?

**Comment by cezarys** [comment]
@PaulAnderie well, at this moment - yes, I thought you want it this way. Do you want one header and one footer field for all forms?

**Comment by PaulAnderie** [comment]
@cezarys no, I'll copy paste the same text in every field. That might be something for the future. 

Thanks

Paul

PS: I'll close this issue.
