### ISSUE TITLE
NEW: Add telephone number as a new field

### ISSUE THREAD

**Issue by PaulAnderie** [prandible/cf7-sevdesk#6]
Pls find the screenshot. Can we match that in the backend as well? 

This work can be charged as an extra milestone.

![Bildschirmfoto_2019-04-05_um_09_26_51](https://user-images.githubusercontent.com/30237486/55611210-2389a180-5785-11e9-9fe6-2f1e65b5f542.png)

**Comment by cezarys** [comment]
this one should be fast so wont take much money

**Comment by cezarys** [comment]
and it's done
